// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFoRsrcGF_BI2Tz9Gq5KKu3-YDiKIRf7k',
    appId: '1:518539965855:web:35060e67062d7bfe8cf9aa',
    messagingSenderId: '518539965855',
    projectId: 'familyassistant2026',
    authDomain: 'familyassistant2026.firebaseapp.com',
    storageBucket: 'familyassistant2026.firebasestorage.app',
    measurementId: 'G-H0K63MK1WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6yfFNk6h3wwSPb6SbtEcpcKIpOIJRuj0',
    appId: '1:518539965855:android:71213931cd48a97b8cf9aa',
    messagingSenderId: '518539965855',
    projectId: 'familyassistant2026',
    storageBucket: 'familyassistant2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nZ7o8EnaICUTax23wUgj5rCepF27mQw',
    appId: '1:518539965855:ios:f39d3ca8e93122668cf9aa',
    messagingSenderId: '518539965855',
    projectId: 'familyassistant2026',
    storageBucket: 'familyassistant2026.firebasestorage.app',
    iosBundleId: 'com.example.familyAssistant',
  );

}